# Generated by Django 5.1.6 on 2025-02-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_image_url_productsimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsImage',
        ),
    ]
